name: Build

on:
  push:
    branches: [main]
    paths-ignore:
    - "**.md"
    - "**.spec.js"
    - ".idea"
    - ".vscode"
    - ".gitignore"
    - ".github/**"
    - "!.github/workflows/build.yml"
    - "__test__/**"
    - "docs/**"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
 